### PR TITLE
Update Cat API query descriptions.

### PR DESCRIPTION
**Pull request by Naarcha-AWS**
Updates the the query parameter descriptions for three APIs, Cat Aliases, Cat Allocation, and Cat Cluster Manager.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kolchfa-aws — COMMENTED** [review]
Please apply changes globally to all instances of the same descriptions. Made suggestions in https://github.com/opensearch-project/documentation-website/pull/8930. cc: @natebower

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Note that it's possible to consolidate schema and use `$ref` if something is repeated all over the place. We could make common parameters for `cat` APIs for example.

**Comment by Naarcha-AWS** [comment]
> Note that it's possible to consolidate schema and use `$ref` if something is repeated all over the place. We could make common parameters for `cat` APIs for example.

Is that something we should do now or flag it for later? For the time being, we could do a simple find and replace to make the descriptions consistent.

**Comment by kolchfa-aws** [comment]
$ref is definitely the preferred long-term strategy.

**Comment by dblock** [comment]
> Is that something we should do now or flag it for later? For the time being, we could do a simple find and replace to make the descriptions consistent.

It's really up to you. I would try to consolidate those into $refs if you're going to do a lot of replacing.

**Comment by dblock** [comment]
Can I merge this?

**Comment by Naarcha-AWS** [comment]
Lets go ahead and merge this one. I'll address the refs in a separate PR.

**Pull request merged**
