### PR TITLE
Remove shared resources.

### PR DESCRIPTION
**Pull request by dblock**
### Description

The use of shared resource is an anti-pattern that ties together unrelated concepts.  A simple example is of `ChapterReader` that is only needed by `ChapterEvaluator`. By introducing a shared resource we start treating the spec, reader and evaluator as singletons in a way that combines them in 1 place, creating unneeded interdependencies. The one thing we do need to pass around is the actual spec, which makes sense as all these classes use the spec in some way. I think the resulting code is a lot clearer (and much shorter, especially in tests where we don't need to pre-create anything).

I also cleaned up some test befores/after's.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nhtruong** [comment]
I believe @Xtansia's https://github.com/opensearch-project/opensearch-api-specification/pull/302 is already handling this.

**Comment by dblock** [comment]
> I believe @Xtansia's #302 is already handling this.

Yes, but mine is much simpler because it removes unnecessary `this._stuff`. I can do it on top of @Xtansia's PR too.

**Comment by nhtruong** [comment]
Got it. Although, I'm afraid you guys are probably stepping on each other's toe haha.

**Comment by dblock** [comment]
> Got it. Although, I'm afraid you guys are probably stepping on each other's toe haha.

Yes, I should have looked. It bugged me so I went ahead and made the change. I don't mind doing the work twice or throwing it out :)

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-api-specification/pull/302 addressed this, closing

**Pull request closed without merging**
