### PR TITLE
adding async search tests for OS 3.0 version 

### PR DESCRIPTION
**Pull request by Tokesh**
### Description
Hello everyone! During the previous PR, we noticed that async search was not working in the OS 3.0 build. They have already fixed it, so we can use async search in version 3.0 as well.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Tokesh** [comment]
I think I can add ```skip-changelog``` tag to this PR

**Review by dblock — CHANGES_REQUESTED** [review]
Looks good. Can you please rebase this, there's 22 commits ;)

**Comment by Tokesh** [comment]
> Looks good. Can you please rebase this, there's 22 commits ;)

Ready for your review! :)
There was a bug where asynchronous search didn't work in version 3.0. It's cool that we found it and it's already fixed!

**Review by dblock — APPROVED** [review]

**Comment by nhtruong** [comment]
> Ready for your review! :) There was a bug where asynchronous search didn't work in version 3.0. It's cool that we found it and it's already fixed!
@Tokesh That's wonderful!! Thank you so much!

**Pull request merged**
