### PR TITLE
[Docs] Descriptions for rank eval and mterm parameters

### PR DESCRIPTION
**Pull request by Naarcha-AWS**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by natebower** [comment]
@Naarcha-AWS Can we reopen this for editorial review? Thanks!

**Comment by dblock** [comment]
@natebower Sorry, this got merged without it. Let's think about a workflow where we can wait for editorial reviews for content if this is something we can do continuously moving forward?

**Comment by natebower** [comment]
@dblock No worries. That is our current workflow 😄. @Naarcha-AWS will coordinate review(s) and notify when ready to merge. Thanks!

**Comment by dblock** [comment]
@Naarcha-AWS @natebower Probably easiest is to keep these in draft until they can be merged?

**Pull request merged**
