### PR TITLE
spec: add plugins to NodeInfoSettings

### PR DESCRIPTION
**Pull request by Jakob3xD**
### Description
Add plugins to NodeInfoSettings

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-api-specification/issues/441

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
Thanks! Care to add a test that has a response with this field?

**Comment by Jakob3xD** [comment]
> Thanks! Care to add a test that has a response with this field?

I am not quite sure how to do this as the response contains as map with a random node id.

But I added the option to the docker env that is responsible for the plugins property to show up.

**Comment by dblock** [comment]
> I am not quite sure how to do this as the response contains as map with a random node id.

You don't actually need to verify the content. As long as the response has the missing field it will validate it against the spec. Try without the fix and it should fail, then with the fix it will pass.

**Comment by Jakob3xD** [comment]
> You don't actually need to verify the content. As long as the response has the missing field it will validate it against the spec. Try without the fix and it should fail - I imagine with the change to the docker options it's failing now? With the fix it will pass.

Yup, fails without the plugins.
https://github.com/Jakob3xD/opensearch-api-specification/actions/runs/10036637738/job/27734769941

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Merged, thank you!

**Comment by dblock** [comment]
@Jakob3xD why did we add `plugins.index_state_management.job_interval=1` here?

**Comment by Jakob3xD** [comment]
> @Jakob3xD why did we add `plugins.index_state_management.job_interval=1` here?

The setting gets returned on node info calls. With this it gets returned by the api and we can test against it. Otherwise it would be omitted.

**Comment by dblock** [comment]
Can it be set via an API like [here](https://github.com/opensearch-project/opensearch-api-specification/blob/main/tests/sql/explain.yaml#L15)? I am thinking we need some way to set and unset these and other settings across tests.

**Comment by dblock** [comment]
I tried to do this in https://github.com/opensearch-project/opensearch-api-specification/pull/471 in which I added a test that ensures the response contains the `job_interval` value. You can set cluster settings, but it has no effect on the response from nodes unfortunately. There's no way to set a node setting via API.

**Pull request merged**
