### PR TITLE
update with more accurate numeric type in _core.yaml

### LINKED ISSUE #596: [BUG] inaccurate numeric type
### What is the bug?
there are many places using generic "number" as numeric type. 

### How can one reproduce the bug?
example: https://github.com/opensearch-project/opensearch-api-specification/blob/939a292753eeb1b3bffdf5ed4f3039ab5edd2f04/spec/schemas/_core.bulk.yaml#L56

### What is the expected behavior?
should use more accurate definition for numeric types. 
https://swagger.io/docs/specification/v3_0/data-models/data-types/

### PR DESCRIPTION
**Pull request by amberzsy**
### Description
for _core.yaml

max_docs (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractBaseReindexRestHandler.java#L117

from (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/search/internal/SearchContext.java#L368

indices_boost (float) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java#L1340C20-L1340C99

min_score (float) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java#L1281

size (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java#L170

terminate_after (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java#L193

took / ingest_tool (int64) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/action/bulk/BulkResponse.java#L201

num_freed (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/action/search/ClearScrollResponse.java#L77 

count (long) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/client/rest-high-level/src/main/java/org/opensearch/client/core/CountResponse.java#L60

metric_score (double) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/modules/rank-eval/src/main/java/org/opensearch/index/rankeval/EvalQueryQuality.java#L61

num_reduce_phases (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/action/search/SearchResponse.java#L412

requestsPerSecondString (float) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractBaseReindexRestHandler.java#L160

requests_per_second (float) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/modules/reindex/src/main/java/org/opensearch/index/reindex/RethrottleRequest.java#L53

if_primary_term (int64) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java#L236

max_concurrent_searches (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/modules/rank-eval/src/main/java/org/opensearch/index/rankeval/RankEvalSpec.java#L119

max_concurrent_shard_requests (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/rest/action/search/RestMultiSearchAction.java#L138

pre_filter_shard_size (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/action/search/SearchRequest.java#L82

batched_reduce_size (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/action/search/SearchRequest.java#L108

suggest_size (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java#L334

retry_on_conflict (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java#L238 

scroll_size (int32) -> https://github.com/opensearch-project/OpenSearch/blob/4e3a6d038dfc37660c7b9e47f570a32b0f2be4d4/server/src/main/java/org/opensearch/index/reindex/AbstractBulkByScrollRequest.java#L70

### Issues Resolved
#596

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Maybe worth writing some hacky automation to sync these? :)

You might find https://github.com/dblock/opensearch-api interesting. I was trying to produce the API spec at runtime, which ended up being useful to do API coverage in this repo. Maybe it can produce some API specs for objects/shapes using reflection?

**Comment by amberzsy** [comment]
> Maybe worth writing some hacky automation to sync these? :)
> 
> You might find https://github.com/dblock/opensearch-api interesting. I was trying to produce the API spec at runtime, which ended up being useful to do API coverage in this repo. Maybe it can produce some API specs for objects/shapes using reflection?

ohh. nice. 

yeah, we had similar discussion yesterday 
1. how should we do version management. currently specs version not align with OpenSearch Core API release (v2.17, v2.16 etc). 
2. how the api/schema release work in OS project, as we have specs, OS core, all kinds of plugins etc. how to make sure all keep in-sync reg API/schema. 
3. we are building the tooling/lib to generate proto from specs, still evaluate if we want to  contribute back to https://github.com/OpenAPITools/openapi-generator (not sure how open they are to accept PRs and proposals) or build different tooling based on existing generator tool.

**Comment by dblock** [comment]
I think I know the answers for (1) and (2).

> 1. how should we do version management. currently specs version not align with OpenSearch Core API release (v2.17, v2.16 etc).

The spec is properly annotated with `x-version-added`, `removed`, etc, and covers all versions of the product. So this should not be a problem. If you need to generate a spec exactly for a given version it's also possible with tools in this repo.

> 2. how the api/schema release work in OS project, as we have specs, OS core, all kinds of plugins etc. how to make sure all keep in-sync reg API/schema.

Using those `x-` annotations above and producing the output for specific versions/ranges.

**Comment by amberzsy** [comment]
> Maybe worth writing some hacky automation to sync these? :)

take a look at  https://github.com/dblock/opensearch-api, it's something good to start with. but i'm not sure if its feasible to generate comprehensive schema definition accurately without have certain enforcement to request PR owner to update proto/spec (e.g build.gradle check spec and proto insync and integration test exist etc. )

**Pull request merged**
