### PR TITLE
Add Persian stem token filter

### PR DESCRIPTION
**Pull request by ebraminio**
### Description
Add Persian stem token filter API documentation

### Issues Resolved
Related to https://github.com/opensearch-project/OpenSearch/pull/14847

This is based on PorterStemTokenFilter

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
Thanks!

Please write a test for it and add to CHANGELOG.

**Comment by ebraminio** [comment]
@dblock Added the changelog 😊 I'm yet figuring out how to add a test as there is not any test for any other filter as far as I can see

**Comment by dblock** [comment]
> @dblock Added the changelog 😊 I'm yet figuring out how to add a test as there is not any test for any other filter as far as I can see

Yes, appreciate if you could write some for other filters as well, start with something simple and work from there. We have a testing guide: https://github.com/opensearch-project/opensearch-api-specification/blob/main/TESTING_GUIDE.md, too.

Since this is in the next version you will have to bump the docker hub ref in CI as well, https://github.com/opensearch-project/opensearch-api-specification/blob/main/.github/workflows/test-spec.yml#L29.

**Comment by dblock** [comment]
Finishing this in https://github.com/opensearch-project/opensearch-api-specification/pull/592.

**Pull request closed without merging**
