### PR TITLE
Updates the missing item types for security API related schemas

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
This PR updates missing `items` property for parent properties of `array` type in the security schema.

### Issues Resolved
 -  Related comment: https://github.com/opensearch-project/opensearch-api-specification/issues/233#issuecomment-2228802285

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
Add a test please into `tests` and update CHANGELOG?

**Comment by nhtruong** [comment]
@dblock the recent PRs fail with [this](https://github.com/opensearch-project/opensearch-api-specification/actions/runs/9942617228/job/27464489905?pr=420#step:6:87)

**Comment by dblock** [comment]
> @dblock the recent PRs fail with [this](https://github.com/opensearch-project/opensearch-api-specification/actions/runs/9942617228/job/27464489905?pr=420#step:6:87)

I'm looking into it.

**Comment by DarshitChanpura** [comment]
@dblock I have a work-in-progress item for tests. I'll raise a separate PR to add tests for all security related APIs.

**Comment by dblock** [comment]
> @dblock I have a work-in-progress item for tests. I'll raise a separate PR to add tests for all security related APIs.

We want to avoid regressions, so maybe PR the tests first?

Either way this PR should be rebased and pass existing tests.

**Comment by DarshitChanpura** [comment]
i'll mark this as draft meanwhile.

**Comment by DarshitChanpura** [comment]
Closing this as changes will be covered by #439

**Pull request closed without merging**
