### PR TITLE
Rename Bytes Components

### PR DESCRIPTION
**Pull request by Jakob3xD**
### Description
Coming from https://github.com/opensearch-project/opensearch-api-specification/pull/552
Adjust the Component names.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Jakob3xD** [comment]
@Xtansia is the naming better now?

**Comment by dblock** [comment]
> @Xtansia is the naming better now?

I like it, leaving for @Xtansia to review.

**Comment by nhtruong** [comment]
Looks good to me. Dont forget to update the changelogs

**Comment by dblock** [comment]
We can skip changelog since this was part of #552, but up to you @Jakob3xD.

**Review by Xtansia — APPROVED** [review]

**Comment by Xtansia** [comment]
Thank you @Jakob3xD, looks great!

**Pull request merged**
